---

- hosts: web
<<<<<<< HEAD
=======

  vars:
   root_password: 'root'

>>>>>>> 32d22b8465be3145b0d494305df018eb47d99e6d
  tasks:
  - name: installation Mariadb
    dnf:
     name: "{{ item }}"
     state: present
    loop:
     - mariadb
     - mariadb-server
     - python3-PyMysql
  - name: activation mariadb
    systemd:
     name: mariadb
     state: started
     enabled: yes
  - name: ajout .my.cnf conf mariadb
    copy:
     src: .my.cnf
     dest: /root/.my.cnf
  - name: Ajout du user mariadb 'ludo' avec  password '12345'  et tout privileges
    mysql_user:
     name: ludo
     password: 12345
     priv: '*.*:ALL'
     state: present
