---

- hosts: 172.31.107.24

  vars:
   root_password: 'root'

  tasks:
  - name: installation Mariadb
    apt:
     name: "{{ item }}"
     state: present
    loop:
     - mariadb-client
     - mariadb-server
     - python3-pymysql
  - name: activation mariadb
    systemd:
     name: mariadb
     state: started
     enabled: yes
  - name: ajout .my.cnf conf mariadb
    copy:
     src: .my.cnf
     dest: /root/.my.cnf
  - name: Ajout du user mariadb 'ludo' avec  password '12345'  et tout privileges
    mysql_user:
     name: ludo
     password: 12345
     priv: '*.*:ALL'
     state: present
